services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: roleradar_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_SERVICE_GRPC_PORT=6334
    networks:
      - roleradar_network
    restart: unless-stopped
    labels:
      - "project=roleradar"
      - "service=qdrant"

  # Superlinked Server (CPU Mode)
  superlinked:
    build:
      context: ./superlinked_app
      dockerfile: Dockerfile
    container_name: roleradar_superlinked
    env_file:
      - ./superlinked_app/.env
    environment:
      - GPU_EMBEDDING_THRESHOLD=0
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - roleradar_network
    depends_on:
      - qdrant
    restart: unless-stopped
    labels:
      - "project=roleradar"
      - "service=superlinked"
    # Wait for backend service to be ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roleradar_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - roleradar_network
    depends_on:
      - superlinked
    restart: unless-stopped
    labels:
      - "project=roleradar"
      - "service=frontend"
    # Wait for frontend service to be ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  roleradar_network:
    name: roleradar_network

volumes:
  qdrant_data:
    labels:
      - "project=roleradar"
      - "service=qdrant"
